# Generated by Django 4.2.7 on 2024-01-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_useraddress_delete_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='user_image',
        ),
    ]
