# Generated by Django 4.2.7 on 2024-01-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='dislike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
