# Generated by Django 4.2.7 on 2024-01-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_postmodel_dislike_remove_postmodel_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedislikemodel',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
    ]
