# Generated by Django 4.2.7 on 2024-01-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_likedislikemodel_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='like_dislike',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='dislike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='LikeDislikeModel',
        ),
    ]
