# Generated by Django 4.2.7 on 2024-01-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_remove_postmodel_dislike_remove_postmodel_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='like',
        ),
    ]
