# Generated by Django 4.2.7 on 2024-01-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_remove_postmodel_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='like_unlike',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='like_dislike',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.likedislikemodel'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post/media/images/'),
        ),
    ]
