# Generated by Django 4.2.7 on 2024-01-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_remove_likedislikemodel_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedislikemodel',
            name='limit_decrease',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
