# Generated by Django 4.2.7 on 2024-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_likedislikemodel_limit_decrease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedislikemodel',
            old_name='limit_decrease',
            new_name='like_permi',
        ),
        migrations.AddField(
            model_name='likedislikemodel',
            name='dislike_permi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
