# Generated by Django 4.2.7 on 2024-01-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_rename_limit_decrease_likedislikemodel_like_permi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislikemodel',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.postmodel'),
        ),
    ]
