# Generated by Django 4.2.7 on 2024-01-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_alter_likedislikemodel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='post_dislike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='post_like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
