# Generated by Django 4.2.7 on 2024-01-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_postmodel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='post/profile/images/'),
        ),
    ]
