# Generated by Django 4.2.7 on 2024-01-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_useraddress_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='user_image',
        ),
    ]
