# Generated by Django 4.2.7 on 2024-02-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_remove_useraddress_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='post/media/user_image/'),
        ),
    ]
