# Generated by Django 4.2.7 on 2024-02-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_useraddress_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='user_image',
        ),
    ]
